version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}
      - run: sudo apt-get update && sudo apt-get install default-jre
      - run: sudo npm install -g npm
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run:
          name: run eslint
          command: npm run audit-ci

      - run:
          name: run eslint
          command: npm run lint

      - run:
          name: run tests incl coverage
          command: npm run test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm publish --access=public

workflows:
  version: 2

  build-and-test:
    jobs:
      - build

  deploy-npm:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
      - deploy:
          context: Production
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
